#!/usr/bin/automate -s std-default,std-c
@etc{
	src/heirloom/file/magic
}
%bsd{
	src/bsd/chroot/chroot
	src/bsd/cut/cut
	src/bsd/diff/diff
	src/bsd/expr/expr
	src/bsd/patch/patch
	src/bsd/readlink/readlink
	src/bsd/xargs/xargs
}
%heirloom{
	src/heirloom/comm/comm
	src/heirloom/csplit/csplit
	src/heirloom/date/date
	src/heirloom/ed/ed
	src/heirloom/expand/expand
	src/heirloom/expand/unexpand
	src/heirloom/file/file
	src/heirloom/find/find
	src/heirloom/fold/fold
	src/heirloom/getconf/getconf
	src/heirloom/grep/egrep
	src/heirloom/grep/fgrep
	src/heirloom/grep/grep
	src/heirloom/groups/groups
	src/heirloom/join/join
	src/heirloom/logname/logname
	src/heirloom/nice/nice
	src/heirloom/nl/nl
	src/heirloom/nohup/nohup
	src/heirloom/od/od
	src/heirloom/paste/paste
	src/heirloom/pr/pr
	src/heirloom/sed/sed
	src/heirloom/sort/sort
	src/heirloom/split/split
	src/heirloom/stty/stty
	src/heirloom/sync/sync
	src/heirloom/test/test
	src/heirloom/time/time
	src/heirloom/touch/touch
	src/heirloom/tr/tr
	src/heirloom/tsort/tsort
	src/heirloom/tty/tty
	src/heirloom/uniq/uniq
	src/heirloom/what/what
}
@program{
	${%bsd}
	${%heirloom}
}
@manpage{
	src/bsd/chroot/chroot.8
	src/bsd/cut/cut.1
	src/bsd/diff/diff.1
	src/bsd/expr/expr.1
	src/bsd/patch/patch.1
	src/bsd/readlink/readlink.1
	src/bsd/xargs/xargs.1
	src/heirloom/comm/comm.1
	src/heirloom/csplit/csplit.1
	src/heirloom/date/date.1
	src/heirloom/ed/ed.1
	src/heirloom/expand/expand.1
	src/heirloom/expand/unexpand.1
	src/heirloom/file/file.1
	src/heirloom/find/find.1
	src/heirloom/fold/fold.1
	src/heirloom/getconf/getconf.1
	src/heirloom/grep/egrep.1
	src/heirloom/grep/fgrep.1
	src/heirloom/grep/grep.1
	src/heirloom/groups/groups.1
	src/heirloom/join/join.1
	src/heirloom/logname/logname.1
	src/heirloom/nice/nice.1
	src/heirloom/nl/nl.1
	src/heirloom/nohup/nohup.1
	src/heirloom/od/od.1
	src/heirloom/paste/paste.1
	src/heirloom/pr/pr.1
	src/heirloom/sed/sed.1
	src/heirloom/sort/sort.1
	src/heirloom/split/split.1
	src/heirloom/stty/stty.1
	src/heirloom/sync/sync.1m
	src/heirloom/test/test.1
	src/heirloom/time/time.1
	src/heirloom/touch/touch.1
	src/heirloom/tr/tr.1
	src/heirloom/tsort/tsort.1
	src/heirloom/tty/tty.1
	src/heirloom/uniq/uniq.1
	src/heirloom/what/what.1
}
$%bsd{
	library{
		env{
			CPPFLAGS{
				command{
					echo
					$CPPFLAGS
					-Isrc/bsd
				}
			}
		}
	}
}
src/bsd/diff{
	transform{
		${%%glob-edit}
		glob:src/bsd/diff/*.c
		edit:sed "s;$$;.o;"
	}
}
src/bsd/patch{
	transform{
		${%%glob-edit}
		glob:src/bsd/patch/*.c
		edit:sed "s;$$;.o;"
	}
}
$%heirloom{
	library{
		env{
			CPPFLAGS{
				command{
					echo
					$CPPFLAGS
					-DSU3BIN="${BINDIR}"
					-DDEFBIN="${BINDIR}"
					-DCCSBIN="${BINDIR}"
					-DUCBBIN="${BINDIR}"
					-DSHELL="${BINDIR}/sh"
					-DMAGIC="${ETCDIR}/magic"
					-Dfunc=test
					-D_DEFAULT_SOURCE
					-D__GLIBC__
					-D__dietlibc__
					-DSU3
					-DSUS
					-Isrc/heirloom
					-Isrc/heirloom/libcommon
					-Isrc/heirloom/libuxre
					-Isrc/heirloom/libwchar
				}
			}
		}
		src/heirloom/libuxre/libuxre.a
		src/heirloom/libcommon/libcommon.a
	}
}
src/heirloom/expand/expand{
	src/heirloom/expand/tablist.c.o
}
src/heirloom/expand/unexpand{
	src/heirloom/expand/tablist.c.o
}
%heirloom-grep-deps{
	src/heirloom/grep/alloc.c.o
	src/heirloom/grep/grep.c.o
	src/heirloom/grep/grid.c.o
	src/heirloom/grep/plist.c.o
}
src/heirloom/grep/egrep{
	${%heirloom-grep-deps}
	src/heirloom/grep/svid3.c.o
}
src/heirloom/grep/fgrep{
	${%heirloom-grep-deps}
	src/heirloom/grep/svid3.c.o
	src/heirloom/grep/ac.c.o
}
src/heirloom/grep/grep{
	${%heirloom-grep-deps}
	src/heirloom/grep/rcomp.c.o
	src/heirloom/grep/sus.c.o
	src/heirloom/grep/ac.c.o
}
src/heirloom/sed/sed{
	transform{
		${%%glob-edit}
		glob:src/heirloom/sed/*.c
		edit:sed "s;$$;.o;"
	}
}
src/heirloom/test/test{
	transform{
		${%%glob-edit}
		glob:src/heirloom/test/*.c
		edit:sed "s;$$;.o;"
	}
}
src/heirloom/grep/egrep.c{
	command:$YACC -o $3 $:{@}
	src/heirloom/grep/egrep.y
}
src/heirloom/libcommon/libcommon.a{
	transform{
		${%%glob-edit}
		glob:src/heirloom/libcommon/*.c
		edit:sed "s;$$;.o;"
	}
	${default.a}
}
src/heirloom/libuxre/libuxre.a{
	transform{
		${%%glob-edit}
		glob:src/heirloom/libuxre/*.c
		edit:sed "s;$$;.o;"
	}
	${default.a}
}
install-program{
	command{
		ln -s test "${DESTDIR}${PREFIX}${BINDIR}/["
	}
}
